hw/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name="logout"),

    # QSTNRS
    path('tests/', views.tests, name='tests'),
    path('tests/overview', views.tests_overview, name='tests_overview'),
    path('tests/<int:person_id>/<int:questionnaire_id>', views.person_test, name='person_test'),
    path('tests/subbase', views.persons_with_tests_and_signature, name='person_subbase'),


    # JSM HW
    path('hw/jsm/', views.jsm, name='jsm'),
    path('hw/jsm/trans/', views.jsm_trans, name='jsm_trans'),
    path('hw/jsm/trans/<int:indx>/ps', views.jsm_ps, name='jsm_ps'),
    path('hw/jsm/trans/<int:indx>/ps', views.jsm_ps_minus, name='jsm_ps_minus'),

    # JSM QSTNRS
    path('research/similarities_q/', views.similarities_q_view, name='similarities_q'),
    path('research/similarities_gw/', views.similarities_gw_view, name='similarities_gw'),
    path('research/similarities_general/', views.similarities_general_view, name='similarities_general'),
    path('research/jsm_choose_option/', views.jsm_choose_option_view, name='jsm_choose_option'),
    path(r'research/potential_hypotheses/', views.potential_hypotheses_view, name='potential_hypotheses'),

    # HW GEN
    path('hw/', views.person_list, name='person_list'),
    url(r'^hw/person/(?P<pk>\d+)[/|]$', views.PersonDetailView.as_view(), name='person_detail'),
    path('hw/person/add_person/', views.create_person, name='create_person'),
    path('hw/person/edit_person/<int:id>/', views.edit_person, name='edit_person'),
    path('hw/person/delete_person/<int:id>/', views.delete_person, name='delete_person'),
    path(r'hw/person/<int:person_id>/add_set/', views.create_set, name='create_set'),
    path(r'hw/person/<int:person_id>/delete_set/<int:id>/', views.delete_set, name='delete_set'),
    path(r'hw/person/<int:person_id>/edit_set/<int:id>/', views.edit_set, name='edit_set'),
    path(r'hw/person/<int:person_id>/general_writing/', views.general_writing, name='general_writing'),
    path(r'hw/person/<int:person_id>/general_writing/delete/<int:writing_id>',
         views.delete_general_writing, name='delete_general_writing'),

    path('ajax/load-gen-values/', views.load_values, name='ajax_load_values'),
    path(r'general_writing/gen_sign_type/', views.gen_sign_type, name='gen_sign_type'),
    path(r'general_writing/gen_sign_type/delete/<int:type_id>', views.delete_gen_sign_type,
         name='delete_gen_sign_type'),
    path(r'general_writing/gen_sign_type/edit/<int:type_id>', views.edit_gen_sign_type, name='edit_gen_sign_type'),

    path(r'general_writing/gen_sign_type/<int:type_id>/gen_sign_value/',
         views.gen_sign_value, name='gen_sign_value'),
    path(r'general_writing/gen_sign_type/<int:type_id>/gen_sign_value/delete/<int:value_id>',
         views.delete_gen_sign_value, name='delete_gen_sign_value'),

    # HW PARTIAL
    path(r'hw/person/<int:person_id>/partial_writing/', views.partial_writing, name='partial_writing'),
    path(r'hw/person/<int:person_id>/partial_writing_v2/', views.partial_writing_v2, name='partial_writing_v2'),
    path(r'hw/person/<int:person_id>/partial_writing/delete/<int:writing_id>',
         views.delete_partial_writing, name='delete_partial_writing'),
    path('ajax/load-letters/', views.load_letters, name='ajax_load_letters'),
    path('ajax/load-partial-values/', views.load_part_values, name='ajax_load_part_values'),
    path('ajax/load-partial-value-concretizations/',
         views.load_part_value_concretizations,
         name='ajax_load_part_value_concretizations'),
    path('ajax/load-part-fle/', views.load_part_fle, name='ajax_load_part_fle'),
    path('ajax/load-part-sle/', views.load_part_sle, name='ajax_load_part_sle'),
    path('ajax/load-part-flec/', views.load_part_flec, name='ajax_load_part_flec'),
    path('ajax/load-part-slec/', views.load_part_slec, name='ajax_load_part_slec'),

    path(r'hw/person/<int:person_id>/partial_writing/transcription', views.create_transcription, name='transcription'),
    path('ajax/load-transcription/', views.load_transcription, name='ajax_load_transcription'),
    path(r'hw/person/<int:person_id>/partial_writing/transcription/delete/<int:set_id>', views.delete_transcription),

    # PART SIGN
    path(r'hw/partial_writing/part_sign/', views.part_sign, name='part_sign'),
    path(r'hw/partial_writing/part_sign/delete/<int:sign_id>', views.delete_part_sign, name='delete_part_sign'),
    # PART TYPE
    path(r'hw/partial_writing/part_sign_type/', views.part_sign_type, name='part_sign_type'),
    path(r'hw/person/<int:person_id>/partial_writing/part_sign_type/', views.part_sign_type,
         name='part_sign_type_person'),
    path(r'hw/partial_writing/part_sign_type/delete/<int:type_id>', views.delete_part_sign_type,
         name='delete_part_sign_type'),

    # PART VALUE
    path(r'hw/partial_writing/part_sign_type/<int:type_id>/part_sign_value/', views.part_sign_value,
         name='part_sign_value'),
    path(r'hw/person/<int:person_id>/partial_writing/part_sign_type/<int:type_id>/part_sign_value/',
         views.part_sign_value, name='part_sign_value_person'),
    path(r'hw/partial_writing/part_sign_type/<int:type_id>/part_sign_value/delete/<int:value_id>',
         views.delete_part_sign_value, name='delete_part_sign_value'),

    # PART VALUE CONCRETIZATION
    path(r'hw/person/<int:person_id>/partial_writing/part_sign_type/<int:type_id>/part_sign_value_concretization/',
         views.part_sign_value_concretization, name='part_sign_value_concretization'),
    path(r'hw/partial_writing/part_sign_type/<int:type_id>/part_sign_value_concretization/',
         views.part_sign_value_concretization, name='part_sign_value_concretization'),
    path(r'hw/partial_writing/part_sign_value_concretization/<int:concr_id>/delete/',
         views.delete_part_sign_value_concretization, name='delete_part_sign_value_concretization'),

    # LETTER
    path(r'hw/letter/', views.letter, name='letter'),
    path(r'hw/letter/delete/<int:letter_id>', views.delete_letter, name='delete_letter'),

    # LETTER ELEMENT
    path(r'hw/letter/<int:letter_id>/letter_element', views.letter_element, name='letter_element'),
    path(r'hw/letter/<int:letter_id>/letter_element/delete/<int:letter_element_id>', views.delete_letter_element,
         name='delete_letter_element'),

    # LETTER ELEMENT CONCRETIZATION
    path(r'hw/person/<int:person_id>/partial_writing/<int:letter_element_id>/letter_concretization',
         views.letter_concretization, name='letter_concretization'),
    path(r'hw/letter/<int:letter_id>/letter_element/<int:letter_element_id>/letter_concretization',
         views.letter_concretization, name='letter_concretization'),
    path(r'hw/partial_writing/concretization/<int:concretization_id>/delete',
         views.delete_concretization, name='delete_concretization'),
    path(r'hw/partial_writing/<int:letter_element_id>/<int:concretization_id>/delete',
         views.delete_letter_concretization, name='delete_letter_concretization'),

    # IDENTIFICATION
    path(r'hw/signature_identification/', views.signature_identification, name='signature_identification'),
    path('ajax/load-tests/', views.load_tests, name='ajax_load_tests'),


    # informativeness research
    path(r'hw/informativeness_research/', views.informativeness_research, name='informativeness_research'),
    path(r'hw/group_signs/', views.group_signs, name='group_signs'),
]

main/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from django import forms
from .models import *

from django.forms.widgets import ClearableFileInput


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']


SEX_CHOICES = [
    ('', '---------'),
    ('м', 'муж.'),
    ('ж', 'жен.'),
]


class PersonForm(forms.ModelForm):
    person_surname = forms.CharField(required=True, label="Фамилия")
    person_name = forms.CharField(required=True, label="Имя")
    birthday = forms.DateField(required=False, label="Дата рождения")
    # sex = forms.ChoiceField(choices=SEX_CHOICES, label="Пол")
    sex = forms.CharField(required=False, widget=forms.Select(choices=SEX_CHOICES), label="Пол")

    class Meta:
        model = Person
        fields = ('person_surname',
                  'person_name',
                  'person_patronymic',
                  'birthday',
                  'position',
                  'sex')
        labels = {
            "person_surname": "Фамилия",
            "person_name": "Имя",
            "person_patronymic": "Отчество",
            "birthday": "Дата рождения",
            "position": "Должность",
            "sex": "Пол",
        }


class SetForm(forms.ModelForm):
    verity = forms.BooleanField(required=False, label='Достоверно ли множество')

    class Meta:
        model = HwSet
        fields = ('type',
                  'amount',
                  # 'verity',
                  'test_number',
                  'person')
        labels = {
            'type': 'Тип',
            'amount': 'Количество',
            # 'verity': 'Достоверность',
            'test_number': 'Номер тестового образца',
        }

    def __init__(self, *args, **kwargs):
        person = kwargs.pop('person')
        verity = kwargs.pop('verity')
        super(SetForm, self).__init__(*args, **kwargs)
        self.fields['person'].initial = person
        self.fields['person'].widget = forms.HiddenInput()

        if verity == 0:
            self.fields['verity'].initial = None
        else:
            self.fields['verity'].initial = verity

    def clean_verity(self):
        return 1 if self.cleaned_data['verity'] and self.cleaned_data['verity'] != 0 else 0

    def clean_testnumber(self):
        return self.cleaned_data['test_number'] if self.cleaned_data['test_number'] else '0'


class GenForm(forms.ModelForm):
    set = forms.ModelChoiceField(queryset=None, label='Множество')
    general_sign_value = forms.ChoiceField(label='Значение')
    amount = forms.IntegerField(label='Проявление')
    person = forms.IntegerField()

    class Meta:
        model = HwGeneralSignValue
        fields = ('set', 'general_sign_type', 'general_sign_value')
        labels = {
            "general_sign_type": "Признак"
        }

    def __init__(self, *args, **kwargs):
        person = kwargs.pop('person')
        super(GenForm, self).__init__(*args, **kwargs)
        self.fields['person'].initial = person
        self.fields['set'].queryset = HwSet.objects.filter(person_id__exact=person)
        self.fields['general_sign_value'].queryset = HwGeneralSignValue.objects.none()
        self.fields['person'].widget = forms.HiddenInput()

        if 'general_sign_type' in self.data:
            try:
                general_sign_type_id = int(self.data.get('general_sign_type'))
                self.fields['general_sign_value'].queryset = HwGeneralSignValue.objects.filter(
                    general_sign_type_id=general_sign_type_id)
            except (ValueError, TypeError):
                pass

        elif self.instance.pk:
            print(self.instance.pk)
            self.fields['general_sign_value'].queryset = self.instance.general_sign_type


class PartForm(forms.Form):
    set = forms.ModelChoiceField(required=True, queryset=None, label='Выберите множество')
    first_letter = forms.ModelChoiceField(required=False, queryset=None, label='Первая буква')
    first_letter_element = forms.ModelChoiceField(required=False, queryset=None, label='Элемент первой буквы')
    first_letter_element_concretization = forms.ModelChoiceField(required=True, queryset=None,
                                                                 label='Конкретизация элемента первой буквы')

    second_letter = forms.ModelChoiceField(queryset=None, required=False, label='Вторая буква')
    second_letter_element = forms.ModelChoiceField(queryset=HwLetterElement.objects.all(), required=False,
                                                   label='Элемент второй буквы')
    second_letter_element_concretization = forms.ModelChoiceField(queryset=HwLetterConcretization.objects.all(),
                                                                  required=False,
                                                                  label='Конкретизация элемента второй буквы')

    partial_sign_type = forms.ModelChoiceField(required=True, queryset=HwPartialSignType.objects.all(), label='Признак')
    partial_sign_value = forms.ModelChoiceField(required=True, queryset=HwPartialSignValue.objects.all(),
                                                label='Значение')
    partial_sign_value_concretization = forms.ModelChoiceField(required=False,
                                                               queryset=HwPartialSignValueConcretization.objects.all(),
                                                               label='Конкретизация значения')

    relation_between_concretizations = forms.BooleanField(required=False, label='Связь между конкретизациями букв')
    amount = forms.IntegerField(required=False, label='Проявление')
    person = forms.IntegerField()

    class Meta:
        model = HwPartialSign
        fields = ('set',
                  # 'first_letter',
                  'first_letter_element',
                  'first_letter_element_concretization',
                  'second_letter',
                  'second_letter_element',
                  'second_letter_element_concretization',
                  'partial_sign_type',
                  'partial_sign_value',
                  'relation_between_concretizations',
                  'partial_sign_value_concretization',
                  'amount')
        labels = {
            "partial_sign_type": "Признак"
        }

    def __init__(self, *args, **kwargs):
        person = kwargs.pop('person')
        super(PartForm, self).__init__(*args, **kwargs)
        self.fields['person'].initial = person
        self.fields['person'].widget = forms.HiddenInput()
        self.fields['set'].queryset = HwSet.objects.filter(person_id__exact=person)
        self.fields['first_letter'].queryset = HwTranscription.objects.all()
        self.fields['first_letter_element'].queryset = HwLetterElement.objects.all()
        self.fields['first_letter_element_concretization'].queryset = HwLetterConcretization.objects.all()
        self.fields['second_letter'].queryset = HwTranscription.objects.all()

    def clean_relation(self):
        return 1 if self.cleaned_data['relation_between_concretizations'] and self.cleaned_data[
            'relation_between_concretizations'] != 0 else 0


class TransForm(forms.ModelForm):
    # set = forms.ChoiceField()
    person = forms.IntegerField()
    variant = forms.BooleanField(required=False, label='Вариант')

    # trans = forms.CharField(widget=forms.Textarea)
    # transcription = forms.CharField()

    class Meta:
        model = HwTranscription
        fields = ('set',
                  # 'transcription',
                  'letter',
                  'letter_place',
                  'link_next',
                  # 'variant'
                  )
        labels = {
            "set": "Множество",
            "letter": "Буква",
            "letter_place": "Место",
            "link_next": "Связь",
        }

    def __init__(self, *args, **kwargs):
        person = kwargs.pop('person')
        super(TransForm, self).__init__(*args, **kwargs)
        self.fields['person'].initial = person
        self.fields['person'].widget = forms.HiddenInput()
        self.fields['set'].queryset = HwSet.objects.filter(person_id__exact=person)


class ImgForm(forms.ModelForm):
    # image = forms.ImageField(HwImage, widget=forms.FileInput())

    class Meta:
        model = HwImage
        fields = ('image', 'set')
        labels = {"image": "", }

    def __init__(self, *args, **kwargs):
        set = kwargs.pop('set')
        super(ImgForm, self).__init__(*args, **kwargs)
        self.fields['set'].initial = set
        self.fields['set'].widget = forms.HiddenInput()
        self.fields['image'].widget = MyClearableFileInput()


class MyClearableFileInput(ClearableFileInput):
    initial_text = 'Активное изображение'

main/templates/hw/general_writing.html
{% extends "base_layout.html" %}

{%  block content %}
<style>
    .btn-link {
        color: forestgreen;
    }

    .btn-link:hover {
        color: darkgreen;
        text-decoration: none;
    }

    .btn-outline-secondary:focus {
        background-color: silver;
        color: #4f4f4f;
        border-color: #aaaaaa;
    }
</style>
<div class="container-fluid">
<form method="GET">
    <h3>Выберите множества для показа</h3>
    <select name="first_set">
        <option value="0">---------</option>
        {% for set in sets %}
        <option value="{{ set.pk }}">{{ set }}</option>
        {% endfor %}
    </select>

    <select name="second_set">
        <option value="0">---------</option>
        {% for set in sets %}
        <option value="{{ set.pk }}">{{ set }}</option>
        {% endfor %}
    </select>

    <button onclick="window.location.reload()">Отобразить</button>
    <br><br>
</form>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><b>Редактировать проявление</b></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form method="POST">
      <div class="modal-body">
          <h9>Введите новое значение для проявления</h9>
            <br>
            {% csrf_token %}
            <input hidden="True" name="writing_id" id="writing_id" value="" />
            <input name="amount_sign" id="amount_sign" type="number" value="" />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
        <input type="submit" name="saveModal" type="button" class="btn btn-primary" value="Сохранить"></input>
      </div>
        </form>
    </div>
  </div>
</div>


    <div class="row">
  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
<table id="table1" class="display table">
    {% if true_set %}
    <h3 class="sub-header"><strong> {{ true_set }} </strong></h3>
    <thead>
         <tr>
            <th hidden="True"></th>
            <th hidden="True"></th>
            <th hidden="True"></th>
            <th>Номер</th>
            <th>Признак</th>
            <th>Значение</th>
            <th>Проявление</th>
             <th></th>
          </tr>
         </thead>
    <tbody>
          {% for gen in gen_for_true_set %}
          <tr>
            <td hidden="True">{% url 'delete_general_writing' true_set.person_id gen.general_writing_id %}</td>
            <td hidden="True">{{ gen.general_writing_id }}</td>
            <td hidden="True">{{ gen.amount_sign }}</td>
            <td>{{ gen.general_sign_value.get_number}}</td>
            <td>{{ gen.general_sign_value.general_sign_type }}</td>
            <td>{{gen.general_sign_value.general_sign_value}}</td>
              <td>
             {% if gen.amount_sign %}
               {{gen.amount_sign}}/{{gen.amount_all}}
             {% endif %}
             </td>
            <td></td>
          </tr>
          {% endfor %}
    </tbody>
    {% endif %}
      </table>
  </div>
  <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
    <table id="table2" class="display table">
        {% if false_set %}
        <h3 class="sub-header"><strong>{{ false_set }}</strong></h3>
       <thead>
      <tr>
        <th hidden="True"></th>
        <th hidden="True"></th>
        <th hidden="True"></th>
        <!-- <th hidden="True">PK</th> -->
        <th>Номер</th>
        <th>Признак</th>
        <th>Значение</th>
        <th>Проявление</th>
          <th></th>
      </tr>
      </thead>
        <tbody>
         <tr>
        {% for gen in gen_for_false_set %}
        <td hidden="True">{% url 'delete_general_writing' false_set.person_id gen.general_writing_id %}</td>
        <td hidden="True">{{ gen.general_writing_id }}</td>
        <td hidden="True">{{ gen.amount_sign }}</td>
        <!--
        <td id="pkRow"
            data-delete-url="{% url 'delete_general_writing' false_set.person_id gen.general_writing_id %}"
            data-writing-id="{{ gen.general_writing_id }}"
            data-writing-amount="{{ gen.amount_sign }}">
            {{ gen.general_writing_id }}
        </td> -->
        <td>{{ gen.general_sign_value.get_number}}</td>
        <td>{{ gen.general_sign_value.general_sign_type }}</td>
        <td>{{gen.general_sign_value.general_sign_value}}</td>
              <td>
             {% if gen.amount_sign %}
               {{gen.amount_sign}}/{{gen.amount_all}}
             {% endif %}
             </td>
        <td></td>
      </tr>
      {% endfor %}
        </tbody>
      {% endif %}
      </table>
  </div>
    </div>
<br>
{% if true_set or false_set %}
<div style="width:100%" align="center">
    <p><strong>Добавить новый признак</strong></p>
    <form method="POST" id="genForm" data-cities-url="{% url 'ajax_load_values' %}" novalidate>
        {% csrf_token %}
        <table>
        {{gen_form.as_table}}
        </table>
        <br>
        <button class="btn btn-outline-secondary" type="submit">Добавить</button>
    </form>
    <br>
    <div>
        <button onclick="location.href='{% url 'gen_sign_type' %}' ">Редактировать признаки </button>
        <button onclick="editValue('{% url 'gen_sign_type' %}')">Редактировать значения выбранного признака</button>
        {% if true_set %}
        <button onclick="location.href='{% url 'person_detail' true_set.person_id %}'">Вернуться к множествам респондента</button>
        {% else %}
        <button onclick="location.href='{% url 'person_detail' false_set.person_id %}'">Вернуться к множествам респондента</button>
        {% endif %}

    </div>
</div>
{% endif %}
    </div>
{% endblock %}
 {% block js %}
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.10.18/af-2.3.0/b-1.5.2/b-colvis-1.5.2/b-flash-1.5.2/b-html5-1.5.2/b-print-1.5.2/cr-1.5.0/fh-3.1.4/r-2.2.2/datatables.min.js"></script>
<script>
$(document).ready( function () {

   if ($('#table2 tr').length != 0) {

    var table2 = $('#table2').DataTable({

        "columnDefs": [
            {
            "targets": -1,
            "data": null,
            "defaultContent": "<button id='delete' class='btn btn-link btn-sm'><i class=\"fa fa-trash-o\"></i></button> <button id='edit' class='btn btn-link btn-sm' data-toggle='modal'><i class=\"fa fa-pencil\"></i></button>"
            },
        ],
                    language: {
                        'search' : 'Поиск по таблице:',
                        'paginate': {
                                "next":       "Вперед",
                                "previous":   "Назад"
                        },
                        'info': "Показано c _START_ по _END_ из _TOTAL_ записей",
                    },
                    "bLengthChange": false,
                    pageLength: 5,
    dom: 'B<"clear">lfrtip',
    buttons: {
        name: 'primary',
        buttons: []
        }
       }
    );
    }

   var table1 = $('#table1').DataTable({

        "columnDefs": [
            {
            "targets": -1,
            "data": null,
            "defaultContent": "<button id='delete' class='btn btn-link btn-sm'><i class=\"fa fa-trash-o\"></i></button> <button id='edit' class='btn btn-link btn-sm' data-toggle='modal'><i class=\"fa fa-pencil\"></i></button>"
            },
        ],
                    language: {
                        'search' : 'Поиск по таблице:',
                        'paginate': {
                                "next":       "Вперед",
                                "previous":   "Назад"
                        },
                        'info': "Показано c _START_ по _END_ из _TOTAL_ записей",
                    },
                    "bLengthChange": false,
                    pageLength: 5,
    dom: 'B<"clear">lfrtip',
    buttons: {
        name: 'primary',
        buttons: []

        }}
    );

    $("#id_general_sign_type").change(function () {
      var url = $("#genForm").attr("data-cities-url");
      var typeId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'general_sign_type': typeId
        },
        success: function (data) {
          $("#id_general_sign_value").html(data);
        }
      });
    });

   $('#table1 tbody').on( 'click', '#delete', function () {
        var data = table1.row( $(this).parents('tr') ).data();
        if (confirm("Вы уверены, что хотите удалить признак подписи?")) {
                location.href = data[0];
        }
    } );


    $('#table1 tbody').on( 'click', '#edit', function () {
        var data = table1.row( $(this).parents('tr') ).data();

        $(".modal-body #amount_sign").val( data[2] );
        $(".modal-body #writing_id").val( data[1] );
        $('#exampleModal').modal('show');
    } );


    $('#table2 tbody').on( 'click', '#delete', function () {
        var data = table2.row( $(this).parents('tr') ).data();
        if (confirm("Вы уверены, что хотите удалить признак подписи?")) {
                location.href = data[0];
                // var deleteUrl = $("#pkRow").attr("data-delete-url");
        }
    } );


    $('#table2 tbody').on( 'click', '#edit', function () {
        var data = table2.row( $(this).parents('tr') ).data();
        //var writingId = $("#pkRow").attr("data-writing-id");
        //var amountSign = $("#pkRow").attr("data-writing-amount");
        //alert(writingId);
        //alert(amountSign);

        $(".modal-body #amount_sign").val( data[2] );
        $(".modal-body #writing_id").val( data[1] );
        $('#exampleModal').modal('show');
    } );
} );


    $("#id_general_sign_type").change(function () {
      var url = $("#genForm").attr("data-cities-url");
      var typeId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'general_sign_type': typeId
        },
        success: function (data) {
          $("#id_general_sign_value").html(data);
        }
      });
    });

    function editValue(href) {
      type =  $("#id_general_sign_type").val();
      location.href = href + type + '/gen_sign_value'
    };
</script>
{% endblock %}

main/templates/hw/group_signs.html
{% extends "base_layout.html" %}

{% block nav %}
<style>
    .btn-link {
        color: forestgreen;
    }
</style>

<ul class="nav nav-tabs">
  <li id="uninformative-tab" class="nav-item">
    <a class="nav-link btn-link" href="{% url 'informativeness_research' %}">Малоинформативные признаки</a>
  </li>
  <li id="group-signs-tab" class="nav-item">
    <a class="nav-link btn-link active" href="{% url 'group_signs' %}">Признаки по группам</a>
  </li>
</ul>
{% endblock %}
{%  block content %}


    <div class="col">
        <table class="table table-striped">
            <h4><i>Общее количество положительных гипотез:</i> {{ amount_plus }}</h4>
            <h4><i>Общее количество противоречивых гипотез:</i> {{ amount_des }}</h4>
           <!-- <h3 class="sub-header"><strong> Малоинформативные признаки </strong></h3> -->
            <thead>
                <th class="col-8">Признак</th>
                <th class="col-2">Количество положительных гипотез</th>
                <th class="col-2">Количество противоречивых гипотез</th>
            </thead>
            <tbody>
            {% for sign, amount_plus, amount_des in table %}
                <tr>
                    <td>
                        {{ sign }}
                    </td>
                    <td>
                        {{ amount_plus }}
                    </td>
                    <td>
                        {{ amount_des }}
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}
{% block js %}
<script>
$(document).ready(function(){
  $(".nav-tabs a").click(function(e){
    $(this).tab('show');
    localStorage.setItem('activeTab', $(e.target).attr('href'));
  });
  var activeTab = localStorage.getItem('activeTab');

  if(activeTab){
      $('#myTab a[href="' + activeTab + '"]').tab('show');
  }
});
</script>
{% endblock %}